### ISSUE TITLE
hello, i find the net can not reach when i run the command sh fetch.sh

### ISSUE THREAD

**Issue by GrinAndBear** [AlexYangLi/tf_CFO#1]
hello, i find the net can not reach when i run the command sh fetch.sh,and my internet is normal,so could you check the source ?  it will be very thanking for receiving your answer

**Comment by AlexYangLi** [comment]
hi @GrinAndBear , sorry for getting back to you so late. yeah, i checked and it's fine：
<img width="300" alt="test" src="https://user-images.githubusercontent.com/30424821/42229164-6249fd7a-7f18-11e8-8278-a2ad721ab811.png">
i guess you might need a little help from **VPN**?
