### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by binjiaqm** [AlexYangLi/tf_CFO#2]
What is your memory size?  

My cofiguration: 64bits + 16GB.

store knowledge triples in pickle format...
Traceback (most recent call last):
  File "create_kg.py", line 138, in <module>
    fetch_triple(sys.argv[1], sys.argv[2], sys.argv[3])
  File "create_kg.py", line 111, in fetch_triple
    pickle_save(triples, os.path.join(out_dir, basename+'_triple.pkl'))
  File "/home/iii/tf_CFO/data_preprocess/utils.py", line 67, in pickle_save
    pickle.dump(obj, writer)
MemoryError

**Comment by AlexYangLi** [comment]
Hi @binjiaqm , really sorry for the late reply. Is your problem already solved? Actually I ran this project on server (256GB) so I don't get memoryerror.

**Comment by binjiaqm** [comment]
It is solved by increasing the Swap size.  Thanks.
